name: iOS Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Build app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build web
        run: |
          npm install
          npm run build
          npx cap sync

      - name: Recreate ios project
        run: |
          rm -rf ios
          npx cap add ios

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install pod dependencies
        run: |
          cd ios/App
          pod install

      - name: Build Project
        run: |
          cd ios/App
          project_name=$(xcodebuild -list -json | jq -r '.project.schemes[0]')
          xcodebuild -workspace App.xcworkspace -scheme "$project_name" clean archive -configuration Release -archivePath $project_name.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          
      - name: Create IPA
        run: |
          cd ios/App
          archive_path="$project_name.xcarchive"
          source_dir="${archive_path%/}/Products/Applications"
          new_folder="Payload"
          rm -rf $new_folder
          mkdir $new_folder
          cp -a $source_dir/* $new_folder
          filename=$(find $new_folder -type d -name '*.app' -exec basename {} \; | head -n 1)
          zip -rmq "${filename%.*}.ipa" $new_folder
