name: IOS Upload testflight

on:
    workflow_dispatch:

jobs:
    build:
        name: Upload app
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Upload to TestFlight
              uses: Apple-Actions/upload-testflight-build@master
              with:
                  app-path: App.ipa
                  api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
                  issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
                  api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
